#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build ImmortalWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: false
        type: boolean
      nocache:
        description: 'Clean Building Cache'
        required: false
        default: false
        type: boolean
      repo:
        description: 'Repo URL'
        required: false
        default: https://github.com/immortalwrt/immortalwrt
      branch:
        description: 'Repo Branch'
        required: false
        default: openwrt-25.12
      name:
        description: 'Firmware Name'
        required: false
        default: ImmortalWrt
      feeds_conf:
        description: 'Custom feeds file'
        required: false
        default: 'feeds.conf.default'
      config:
        description: 'Custom build config'
        required: false
        default: '.config'
      kernel_config:
        description: 'Custom kernel build config'
        required: false
        default: 'config-6.12'
      artifact:
        description: 'Upload firmware to artifact'
        required: false
        default: true
        type: boolean
      release:
        description: 'Upload firmware to release'
        required: false
        default: false
        type: boolean
      bindir:
        description: 'Upload bin to artifact'
        required: false
        default: false
        type: boolean

env:
  BEFORE_FEED_SH: before-installing-feed.sh
  AFTER_FEED_SH: after-installing-feed.sh
  TZ: UTC

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
        sudo apt update
        sudo apt -y install erofs-utils tmux gawk
        sudo apt-mark hold azure-cli distro-info-data docker-ce-cli dpkg dpkg-dev git git-man libdpkg-perl libnghttp2-14 libpng16-16t64 powershell xxd
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo apt -y autoremove golang-* --purge
        sudo rm -rf /usr/bin/go /usr/bin/gofmt /usr/lib/go-* /usr/lib/go-[0-9]*
        sudo mkdir -p /workdir
        sudo chown -R $(whoami):$(whoami) /workdir

    - name: Setup go
      uses: actions/setup-go@main
      with:
        go-version: 'stable'
        cache: false
        
    - name: Checkout
      uses: actions/checkout@main

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --depth=1 ${{ inputs.repo }} -b ${{ inputs.branch }} openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Free up disk space
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p -m 777 /mnt/openwrt/dl /mnt/openwrt/staging_dir /mnt/openwrt/build_dir
        rm -rf openwrt/dl openwrt/staging_dir openwrt/build_dir
        ln -sf /mnt/openwrt/dl openwrt/dl
        ln -sf /mnt/openwrt/staging_dir openwrt/staging_dir
        ln -sf /mnt/openwrt/build_dir openwrt/build_dir

    - name: Cache
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        prefix: ${{ github.workspace }}/openwrt
        clean: ${{ inputs.nocache || 'false' }}
        mixkey: 'x86-64'

    - name: Load custom feeds
      run: |
        [ -e ${{ inputs.feeds_conf }} ] && mv ${{ inputs.feeds_conf }} openwrt/feeds.conf.default
        chmod +x $BEFORE_FEED_SH
        cd openwrt
        $GITHUB_WORKSPACE/$BEFORE_FEED_SH

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a -f

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e ${{ inputs.config }} ] && mv ${{ inputs.config }} openwrt/.config
        [ -e ${{ inputs.kernel_config }} ] && mv ${{ inputs.kernel_config }} openwrt/target/linux/x86/${{ inputs.kernel_config }}
        chmod +x $AFTER_FEED_SH
        cd openwrt
        $GITHUB_WORKSPACE/$AFTER_FEED_SH
        cat package/emortal/default-settings/files/99-default-settings

    - name: Set variables
      run: |
        echo "BUILD_TIME=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "BUILD_NUMBER=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        cd openwrt
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=$(cat DEVICE_NAME)" >> $GITHUB_ENV

    - name: Make Easy Update Script happy
      run: |
        sed -i "/exit 0/i\sed -i '/DISTRIB_GITHUB/d' /etc/openwrt_release" openwrt/package/emortal/default-settings/files/99-default-settings
        sed -i "/DISTRIB_GITHUB/a\echo \"DISTRIB_GITHUB=\'https://github.com/${{github.repository}}\'\" >> /etc/openwrt_release" openwrt/package/emortal/default-settings/files/99-default-settings
        sed -i "/exit 0/i\sed -i '/DISTRIB_VERSIONS/d' /etc/openwrt_release" openwrt/package/emortal/default-settings/files/99-default-settings
        sed -i "/DISTRIB_VERSIONS/a\echo \"DISTRIB_VERSIONS=\'${{ env.BUILD_TIME }}_${{ env.BUILD_NUMBER }}\'\" >> /etc/openwrt_release" openwrt/package/emortal/default-settings/files/99-default-settings
        sudo chmod +x openwrt/files/usr/bin/easyupdate.sh

    - name: SSH connection to Actions
      uses: owenthereal/action-upterm@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      with:
        wait-timeout-minutes: 15

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && inputs.bindir == 'true' && !cancelled()
      with:
        name: ${{ inputs.name }}_bin_${{ env.DEVICE_NAME }}_${{ env.BUILD_TIME }}_${{ env.BUILD_NUMBER }}
        path: openwrt/bin

    - name: Get environment path
      id: environment
      if: inputs.bindir == 'true' && !cancelled()
      run: |
        cd openwrt/bin/
        echo "WORKSPACE_DIR=$PWD" >> $GITHUB_ENV
        cd  targets/*/*
        echo "UPLOAD_PATH=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Compressed kernel packages
      uses: thedoctor0/zip-release@master
      if: steps.environment.outputs.status == 'success' && steps.compile.outputs.status == 'success' && !cancelled()
      with:
        type: tar
        path: packages/
        directory: ${{ env.UPLOAD_PATH }}/
        filename: ${{ env.UPLOAD_PATH }}/${{ inputs.name }}_firmware_kernel_packages_${{ env.DEVICE_NAME }}_${{ env.BUILD_TIME }}_${{ env.BUILD_NUMBER }}.tar.gz

    - name: Compressed firmware packages
      uses: thedoctor0/zip-release@master
      if: steps.environment.outputs.status == 'success' && steps.compile.outputs.status == 'success' && !cancelled()
      with:
        type: tar
        path: packages/
        directory: ${{ env.WORKSPACE_DIR }}/
        filename: ${{ env.UPLOAD_PATH }}/${{ inputs.name }}_firmware_packages_${{ env.DEVICE_NAME }}_${{ env.BUILD_TIME }}_${{ env.BUILD_NUMBER }}.tar.gz

    - name: Organize files
      id: organize
      if: inputs.artifact == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory to artifact
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ inputs.name }}_firmware_${{ env.DEVICE_NAME }}_${{ env.BUILD_TIME }}_${{ env.BUILD_NUMBER }}
        path: ${{ env.FIRMWARE }}

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v2
      if: inputs.release == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ env.FIRMWARE }}/*
        name: ${{ inputs.name }} ${{ env.DEVICE_NAME }}
        tag_name: ${{ inputs.name }}_${{ env.DEVICE_NAME }}_${{ env.BUILD_TIME }}_${{ env.BUILD_NUMBER }}

